# Generated by Django 5.0.7 on 2024-07-28 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("userId", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mobileNumber", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("expenseId", models.AutoField(primary_key=True, serialize=False)),
                ("desc", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "createdById",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kuldeepAPI.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpensePaidBy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "expenseId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kuldeepAPI.expense",
                    ),
                ),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kuldeepAPI.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("userId", "expenseId")},
            },
        ),
        migrations.CreateModel(
            name="ExpenseOwedBy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "expenseId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kuldeepAPI.expense",
                    ),
                ),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kuldeepAPI.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("userId", "expenseId")},
            },
        ),
    ]
